version: '3'
services:
    keehost_api:
        build: './api'
    keehost_login:
        build: './login'
    mongo:
        image: 'mongo'
        ports:
            - '27017:27017'
        volumes:
            - './volumes/data/db:/data/db'
    keehost_front:
        image: nginx
        volumes:
            - './nginx.conf:/etc/nginx/nginx.conf'
        ports:
            - "8080:80"
